# post new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYWRmZGFmYTEzN2RhNDIzNTAyZmM0MyIsImlhdCI6MTY3MjM0NzA2N30.MH691f2TjlealE1oppYqTvS3s8lzK68pFk3zS4dSSQY

{
    "title": "Testblog 1",
    "author": "Rango",
    "url": "www.rangocool.com",
    "likes": 10
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Testblog 2",
    "author": "Rango",
    "url": "www.rangocool.com",
    "likes": 10
}

###
# put to blog
PUT http://localhost:3001/api/blogs/63a36e23d2a22a9c0a629f0a
Content-Type: application/json

{
    "title": "oste",
    "author": "pik",
    "url": "www.ost.dk",
    "likes": 10
}

###
# delete all blogs
GET http://localhost:3001/api/blogs/clear/
Content-Type: application/json